
FROM hguomin/devplus:dev

RUN apt-get update && \ 
    apt-get install openjdk-11-jdk-headless ca-certificates-java -y 

RUN apt-get install maven -y && \
    apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64


CMD [ "/bin/bash", "-c", "env >> /var/rt-env && /usr/sbin/sshd -D" ]