FROM hguomin/devplus:dev

RUN apt update && \ 
    apt install wget python3-pip python3.8 -y 
    
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_4.11.0-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

CMD [ "/bin/bash", "-c", "env >> /var/rt-env && /usr/sbin/sshd -D" ]